service: serverless-typescript-jest
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  iam:
    deploymentRole: arn:aws:iam::765557214082:role/ServerlessCloudFormationExecutionRole

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  
  getUser:
    handler: handler.getUser
    events:
      - http:
          path: user/{id}
          method: get
plugins:
  - serverless-offline
  - serverless-esbuild

