service: aws-node-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  
  getUser:
    handler: handler.getUser
    events:
      - http:
          path: user
          method: get
plugins:
  - serverless-offline
