name: create-badge-details
on:
  push:
    branches:
      - master
      - badge
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository onto the runner
        uses: actions/checkout@v3

      - name: Install the specified version of the Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.18.3'

      - name: Install the specified version of npm
        run: npm install npm@8.1.4 -g

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test -- --coverage | tee ./coverage.txt

      - name: Jest coverage comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          hide-summary: true
          coverage-summary-path: ./coverage/coverage-summary.json

      - name: Update Readme with Coverage Html
        run: |
          sed -i '/<!-- Jest Coverage Comment:Begin -->/,/<!-- Jest Coverage Comment:End -->/c\<!-- Jest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.summaryHtml }}\n<!-- Jest Coverage Comment:End -->' ./README.md

      - name: Commit & Push changes to Readme
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.GITHUB_TOKEN }}
