name: create-badge-details
on:
  push:
    branches:
      - master
      - badge
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository onto the runner
        uses: actions/checkout@v3

      - name: Install the specified version of the Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.18.3'

      - name: Install the specified version of npm
        run: npm install npm@8.1.4 -g

      - name: Install dependencies
        run: npm ci

      - name: Run testa  
        run: npm test --coverage

      - name: Jest coverage comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          hide-comment: true
          coverage-summary-path: ./coverage/coverage-summary.json

      - name: Check the output coverage
        run: |
          echo "Coverage Percantage - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Summary Html - ${{ steps.coverageComment.outputs.summaryHtml }}"

      - name: Create the Badge
            if: ${{ github.ref == 'refs/heads/main' }}
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
          gistID: 5e90d640f8c212ab7bbac38f72323f80
          filename: jest-coverage-comment__main.json
          label: Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}%
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: javascript
