name: generate-coverage-badge
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository onto the runner
        uses: actions/checkout@v3

      - name: Install the specified version of the Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.18.3'

      - name: Install the specified version of npm
        run: npm install npm@8.1.4 -g

      - name: Install dependencies
        run: npm install

      - name: Run test and generate coverage badge
        run: npm run make-badges

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "chore: update coverage badge"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
