name: generate-coverage-badge
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository onto the runner
        uses: actions/checkout@v3

      - name: Install the specified version of the Node.js
        run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        nvm install 12.18.3
        npm install npm@8.1.4 -g

      - name: Install dependencies
        run: npm install

      - name: Run test and generate coverage badge
        run: npm run make-badges
