name: generate-coverage-badge
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository onto the runner
        uses: actions/checkout@v3

      - name: Install the specified version of the Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.18.3'

      - name: Install dependencies
        run: npm install

      - name: Run test and generate coverage badge
        run: npm run make-badges
